-- ============================================
-- SETUP COMPLET SNOWFLAKE - NYC TAXI PROJECT
-- ============================================

USE ROLE ACCOUNTADMIN;

-- 1. CRÉATION DE LA BASE DE DONNÉES
CREATE DATABASE IF NOT EXISTS NYC_TAXI_DB;

-- 2. CRÉATION DES SCHÉMAS
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.RAW;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.STAGING;
CREATE SCHEMA IF NOT EXISTS NYC_TAXI_DB.FINAL;

-- 3. CRÉATION DU WAREHOUSE
CREATE WAREHOUSE IF NOT EXISTS NYC_TAXI_WH
  WAREHOUSE_SIZE = 'X-SMALL'
  AUTO_SUSPEND = 60
  AUTO_RESUME = TRUE
  INITIALLY_SUSPENDED = FALSE;

-- 4. CRÉATION DU RÔLE TRANSFORM
CREATE ROLE IF NOT EXISTS TRANSFORM;

-- 5. CRÉATION DE L'UTILISATEUR DBT
CREATE USER IF NOT EXISTS dbt
  LOGIN_NAME = 'dbt'
  MUST_CHANGE_PASSWORD = FALSE
  DEFAULT_WAREHOUSE = 'NYC_TAXI_WH'
  DEFAULT_ROLE = 'TRANSFORM'
  DEFAULT_NAMESPACE = 'NYC_TAXI_DB.RAW';

-- 6. ATTRIBUTION DU RÔLE À L'UTILISATEUR
GRANT ROLE TRANSFORM TO USER dbt;

-- 7. DROITS SUR LE WAREHOUSE
GRANT USAGE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORM;
GRANT OPERATE ON WAREHOUSE NYC_TAXI_WH TO ROLE TRANSFORM;

-- 8. DROITS SUR LA BASE DE DONNÉES
GRANT USAGE ON DATABASE NYC_TAXI_DB TO ROLE TRANSFORM;

-- 9. DROITS SUR LE SCHÉMA RAW (LECTURE SEULE)
GRANT USAGE ON SCHEMA NYC_TAXI_DB.RAW TO ROLE TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_DB.RAW TO ROLE TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB.RAW TO ROLE TRANSFORM;
GRANT SELECT ON ALL VIEWS IN SCHEMA NYC_TAXI_DB.RAW TO ROLE TRANSFORM;
GRANT SELECT ON FUTURE VIEWS IN SCHEMA NYC_TAXI_DB.RAW TO ROLE TRANSFORM;

-- 10. DROITS SUR LE SCHÉMA STAGING (LECTURE + ÉCRITURE)
GRANT USAGE ON SCHEMA NYC_TAXI_DB.STAGING TO ROLE TRANSFORM;
GRANT CREATE TABLE ON SCHEMA NYC_TAXI_DB.STAGING TO ROLE TRANSFORM;
GRANT CREATE VIEW ON SCHEMA NYC_TAXI_DB.STAGING TO ROLE TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_DB.STAGING TO ROLE TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB.STAGING TO ROLE TRANSFORM;

-- 11. DROITS SUR LE SCHÉMA FINAL (LECTURE + ÉCRITURE)
GRANT USAGE ON SCHEMA NYC_TAXI_DB.FINAL TO ROLE TRANSFORM;
GRANT CREATE TABLE ON SCHEMA NYC_TAXI_DB.FINAL TO ROLE TRANSFORM;
GRANT CREATE VIEW ON SCHEMA NYC_TAXI_DB.FINAL TO ROLE TRANSFORM;
GRANT SELECT ON ALL TABLES IN SCHEMA NYC_TAXI_DB.FINAL TO ROLE TRANSFORM;
GRANT SELECT ON FUTURE TABLES IN SCHEMA NYC_TAXI_DB.FINAL TO ROLE TRANSFORM;

-- 12. VÉRIFICATIONS
SHOW DATABASES LIKE 'NYC_TAXI_DB';
SHOW SCHEMAS IN DATABASE NYC_TAXI_DB;
SHOW WAREHOUSES LIKE 'NYC_TAXI_WH';
SHOW ROLES LIKE 'TRANSFORM';
SHOW USERS LIKE 'DBT';
SHOW GRANTS TO ROLE TRANSFORM;
